remote_theme: thelehhman/plainwhite-jekyll

title: Mehdi Imam

plainwhite:
  name: Mehdi Imam
  tagline: C.S Student
  date_format: "%b %-d, %Y"
  
social_links:
  twitter: thelehhman
  github: mehdiimam439
  linkedIn: in/thelehhman # format: locale/username
